  const data = [
            { id: 1, img: "./images/no-image.png", brand: "Chevrolet Niva", number: "АР 415 G", active: true },
            { id: 2, img: "./images/АО0028СЕ.png", brand: "BMW 530D", number: "АО 0028 СЕ", active: true },
            { id: 3, img: "./images/no-image.png", brand: "Богдан", number: "АР 410 G", active: true },
            { id: 4, img: "./images/no-image.png", brand: "Богдан", number: "АР 405 G", active: true },
            { id: 5, img: "./images/no-image.png", brand: "Газ 66", number: "АР 411 G", active: true },
            { id: 6, img: "./images/no-image.png", brand: "Зiл 5301", number: "АР 412 G", active: true },
            { id: 7, img: "./images/no-image.png", brand: "Зiл 433100", number: "АР 406 G", active: true },
            { id: 8, img: "./images/no-image.png", brand: "Зiл 433100", number: "АР 407 G", active: true },
            { id: 9, img: "./images/no-image.png", brand: "Причеп", number: "АР 786 G", active: true },
            { id: 10, img: "./images/no-image.png", brand: "Маз", number: "АР 413 G", active: true },
            { id: 11, img: "./images/no-image.png", brand: "Маз", number: "АР 409 G", active: true },
            { id: 12, img: "./images/no-image.png", brand: "Ford Ranger", number: "АР 404 G", active: true },
            { id: 13, img: "./images/no-image.png", brand: "Причеп", number: "АР 785 G", active: true },
            { id: 14, img: "./images/no-image.png", brand: "Причеп", number: "АР 784 G", active: true },
            { id: 15, img: "./images/no-image.png", brand: "Причеп Спец", number: "АР 783 G", active: true },
            { id: 16, img: "./images/no-image.png", brand: "Renault Duster", number: "АР 408 G", active: true },
            { id: 17, img: "./images/no-image.png", brand: "Ford Tourneo", number: "АР 402 G", active: true },
            { id: 18, img: "./images/no-image.png", brand: "Ford Tourneo", number: "АР 403 G", active: true },
            { id: 19, img: "./images/no-image.png", brand: "Ford Transit", number: "АР 401 G", active: true },
            { id: 20, img: "./images/no-image.png", brand: "Ford Kuga", number: "АР 400 G", active: true },
            { id: 21, img: "./images/no-image.png", brand: "Ford Transit", number: "АР 416 G", active: true },
            { id: 22, img: "./images/no-image.png", brand: "Renault Trafic", number: "ВТ 5527 СМ", active: true },
            { id: 23, img: "./images/no-image.png", brand: "Renault Duster", number: "ВТ 8405 СМ", active: true },
            { id: 24, img: "./images/no-image.png", brand: "Renault Trafic", number: "ВТ 3741 СІ", active: true },
            { id: 25, img: "./images/KA3714EB.png", brand: "Toyota RAV-4 Hybrid", number: "КА 3714 ЕВ", active: true },
            { id: 26, img: "./images/KA7634HT.png", brand: "Toyota RAV 4 Hybrid", number: "КА 7634 НТ", active: true },
            { id: 27, img: "./images/KA1517AT.png", brand: "Toyota RAV-4 Hybrid", number: "KA 1517 AT", active: true },
            { id: 28, img: "./images/AA2652XI.png", brand: "Toyota Proace", number: "AA 2652 XІ", active: true },
            { id: 29, img: "./images/KA0914CK.png", brand: "Toyota C-HR Hybrid", number: "КА 0914 СК", active: true },
            { id: 30, img: "./images/KA0529AO.png", brand: "Toyota Land Cruiser", number: "КА 0529 АО", active: true },
            { id: 31, img: "./images/KA9341EK.png", brand: "Toyota Land Cruiser", number: "КА 9341 ЕК", active: false },
            { id: 32, img: "./images/KA7925BC.png", brand: "Toyota Hilux", number: "КА 7925 ВС", active: false },
            { id: 33, img: "./images/KA9688AP.png", brand: "Lexus LX 450D", number: "КА 9688 АР", active: false },
            { id: 34, img: "./images/no-image.png", brand: "BMW", number: "ВХ ? 694 ? ЕР", active: false },
            { id: 35, img: "./images/АН5000АО-ОА.png", brand: "Toyota Land Cruiser", number: "АН 5000 АО", active: false },
            { id: 36, img: "./images/no-image.png", brand: "Renault Duster", number: "АА 8004 РТ", active: false },
            { id: 37, img: "./images/ВС1203ЕА.png", brand: "Renault Scenic", number: "ВС 1203 ЕА", active: false },
            { id: 38, img: "./images/no-image.png", brand: "Land Rover", number: "ВС 6137 СН", active: false },
            { id: 39, img: "./images/no-image.png", brand: "Renault Trafic", number: "АН 4171 НН - МН", active: false },
            { id: 40, img: "./images/АА0949РІ.png", brand: "Toyota Land Cruiser", number: "АА 0949 РІ", active: false },
            { id: 41, img: "./images/АМ5668ЕІ.png", brand: "Volksvagen Crafter", number: "АМ 5668 ЕІ", active: false },
            { id: 42, img: "./images/АМ1748ЕР.png", brand: "Volkswagen Crafter", number: "АМ 1748 ЕО", active: false },
            { id: 43, img: "./images/ВХ6982ЕР.png", brand: "Dacia Sandero", number: "ВХ 6982 ЕР", active: false },
            { id: 44, img: "./images/АА3492ОО.png", brand: "Ford ", number: "АН 3492 ОО", active: false },
            { id: 45, img: "./images/no-image.png", brand: "BMW", number: "АЕ ? 760 ЕР", active: false },
            { id: 46, img: "./images/АТ9854ЕР.png", brand: "Nissan Qashqai", number: "АТ 9854 ЕР", active: false },
            { id: 47, img: "./images/АВ1055ЕР.png", brand: "Toyota Corolla", number: "АВ 1055 ЕР ", active: false },
            { id: 48, img: "./images/ВІ2317ВА.png", brand: "Mitsubishi Lancer", number: "ВІ 2317 ВА", active: false },
            { id: 49, img: "./images/ВА7714СА.png", brand: "Ford Kuga", number: "ВА 7714 СА", active: false },
            { id: 50, img: "./images/КА5874СА.png", brand: "Hyundai Elantra", number: "КА 5874 СА", active: false },
            { id: 51, img: "./images/no-image.png", brand: "Таврія", number: "АН 4877 ??", active: false },
            { id: 52, img: "./images/no-image.png", brand: "ЗАЗ", number: "АН 4877 МА", active: false },
            { id: 53, img: "./images/no-image.png", brand: "Renault Megane", number: "ВВ 4460 СР", active: false },
            { id: 54, img: "./images/no-image.png", brand: "Газ 2705-434", number: "АХ 4062 ІО", active: false },
            { id: 55, img: "./images/no-image.png", brand: "Ніва Темносиня", number: "?23-33?", active: false },
            { id: 56, img: "./images/no-image.png", brand: "Fiat Doblo", number: "ВВ 5791 СО", active: false },
            { id: 57, img: "./images/no-image.png", brand: "Рута 25D", number: "ВА 1906 ВО", active: false },
            { id: 58, img: "./images/no-image.png", brand: "ПАЗ 4234", number: "ВМ 3848 АА", active: false },
            { id: 59, img: "./images/no-image.png", brand: "Renault Duster", number: "ВМ 4751 СТ", active: false },
            { id: 60, img: "./images/no-image.png", brand: "ГАЗ", number: "ВМ 3674 АК", active: false },
            { id: 61, img: "./images/no-image.png", brand: "ГАЗ", number: "ВМ 3960 АО", active: false },
            { id: 62, img: "./images/no-image.png", brand: "MERLO", number: "EE 18961 ВМ", active: false },
            { id: 63, img: "./images/no-image.png", brand: "МАЗ 5551A2", number: "ВМ 1910 ВВ", active: false },
            { id: 64, img: "./images/no-image.png", brand: "Renault Master", number: "АР 9610 ЕН", active: false },
            { id: 65, img: "./images/no-image.png", brand: "Renault Duster", number: "АР 2269 ЕН", active: false },
            { id: 66, img: "./images/no-image.png", brand: "ВАЗ 2101", number: "ВВ 8753 ЕР", active: false },
            { id: 67, img: "./images/no-image.png", brand: "Поліцейські", number: "1891", active: false },
            { id: 68, img: "./images/no-image.png", brand: "Поліцейські", number: "4949", active: false },
            { id: 69, img: "./images/no-image.png", brand: "Поліцейські", number: "8151", active: false },
            { id: 70, img: "./images/1773.png", brand: "Hyundai", number: "1773", active: false },
            { id: 71, img: "./images/no-image.png", brand: "Chevrolet Suburban", number: "4218", active: false },
            { id: 72, img: "./images/no-image.png", brand: "Renault Master", number: "АР 9610 ЕН", active: false },
            { id: 73, img: "./images/no-image.png", brand: "Renault Duster", number: "АР 2269 ЕН", active: false },
            { id: 74, img: "./images/no-image.png", brand: "Таврiя", number: "1806", active: false },
            { id: 75, img: "./images/no-image.png", brand: "ВАЗ 2109", number: "1810", active: false },
            { id: 76, img: "./images/no-image.png", brand: "ВАЗ 2109", number: "1808", active: false },
            { id: 77, img: "./images/no-image.png", brand: "ВАЗ 2104", number: "0638", active: false },
            { id: 78, img: "./images/no-image.png", brand: "ЗАЗ", number: "0654", active: false },
            { id: 79, img: "./images/no-image.png", brand: "ЗАЗ", number: "0687", active: false },
            { id: 80, img: "./images/no-image.png", brand: "ВАЗ 2107", number: "1805", active: false },
            { id: 81, img: "./images/no-image.png", brand: "ВАЗ 21099", number: "0798", active: false },
            { id: 82, img: "./images/no-image.png", brand: "ВАЗ 2107", number: "0681", active: false },
            { id: 83, img: "./images/no-image.png", brand: "ВАЗ 2107", number: "1414", active: false },
            { id: 84, img: "./images/no-image.png", brand: "ВАЗ 2107", number: "0751", active: false },
            { id: 85, img: "./images/no-image.png", brand: "Volkswagen", number: "0083", active: false },
            { id: 86, img: "./images/no-image.png", brand: "Skoda", number: "0731", active: false },
            { id: 87, img: "./images/no-image.png", brand: "Renault Dokker", number: "1826", active: false },
            { id: 88, img: "./images/no-image.png", brand: "Haval", number: "0687", active: false },
            { id: 89, img: "./images/0224.png", brand: "Ваз 2109", number: "0224", active: false },
            { id: 90, img: "./images/no-image.png", brand: "Ford transit", number: "АА 299 G", active: false },
            { id: 91, img: "./images/no-image.png", brand: "Ваз 2113", number: "АР 4958 ?", active: false },
            { id: 92, img: "./images/no-image.png", brand: "Mitsubishi L200", number: "АХ 3338 АХ", active: false },
            { id: 93, img: "./images/no-image.png", brand: "Газель", number: "0994", active: false },
            { id: 94, img: "./images/no-image.png", brand: "Нiва", number: "АЕ 5173 МК", active: false },
            { id: 95, img: "./images/no-image.png", brand: "Skoda", number: "АЕ 2289 АВ", active: false },
            { id: 96, img: "./images/no-image.png", brand: "Volkswagen lt 35", number: "АХ 8081 ?", active: false },
            { id: 97, img: "./images/no-image.png", brand: "Renault traffic", number: "АХ 6949 СМ", active: false },
            { id: 98, img: "./images/no-image.png", brand: "Citroen jumper", number: "АХ 9906 ВА", active: false },
            { id: 99, img: "./images/no-image.png", brand: "Газель", number: "AX 5930 АР", active: false },
            { id: 100, img: "./images/no-image.png", brand: "Соболь", number: "АХ 0856 АХ", active: false },
            { id: 101, img: "./images/no-image.png", brand: "Renault Duster", number: "ВЕ 9976 ВМ", active: false },
            { id: 102, img: "./images/no-image.png", brand: "Нiва", number: "ВЕ 1369 ВО", active: false },
            { id: 103, img: "./images/no-image.png", brand: "Нiва", number: "ВЕ 9968 ВМ", active: false },
            { id: 104, img: "./images/no-image.png", brand: "Газель", number: "ВЕ 6963 ВО", active: false },
            { id: 105, img: "./images/1757.png", brand: "Peugeot", number: "1757", active: false },
            { id: 106, img: "./images/6965.png", brand: "Skoda", number: "6965", active: false },
            { id: 107, img: "./images/no-image.png", brand: "Нiва", number: "2333", active: false },
            { id: 108, img: "./images/no-image.png", brand: "Renault Duster", number: "СВ 137 В", active: false },
            { id: 109, img: "./images/no-image.png", brand: "Volkswagen Amarok", number: "СВ 144 В", active: false },
            { id: 110, img: "./images/no-image.png", brand: "Поліцейські", number: "1356", active: false },
            { id: 111, img: "./images/0019.png", brand: "Skoda", number: "0019", active: false },
            { id: 112, img: "./images/1489.png", brand: "Renault", number: "1489", active: false },
            { id: 113, img: "./images/1217.png", brand: "Renault Kangoo", number: "1217", active: false },
            { id: 114, img: "./images/no-image.png", brand: "Suzuki", number: "? 3367 ?", active: false },
            { id: 115, img: "./images/no-image.png", brand: "УАЗ 3909", number: "АА 3199 РХ", active: false },
            { id: 116, img: "./images/no-image.png", brand: "УАЗ 3909", number: "АА 3197 РХ", active: false },
            { id: 117, img: "./images/no-image.png", brand: "Volksvagen ", number: "АХ 0860 СК", active: false },
            { id: 118, img: "./images/no-image.png", brand: "Ваз 2109", number: "АР 5224 НЕ", active: false },
            { id: 119, img: "./images/no-image.png", brand: "Богдан", number: "0643", active: false },
            { id: 120, img: "./images/no-image.png", brand: "Toyota Land Cruiser", number: "0657", active: false },
            { id: 121, img: "./images/no-image.png", brand: "Ваз 21013", number: "4958", active: false },
            { id: 122, img: "./images/КА4435АХ.png", brand: "Subaru Forester", number: "КА 4435 АХ", active: false },
            { id: 123, img: "./images/АА1114ЕР.png", brand: "Porsche Cayenne", number: "АА 1114 ЕР", active: false },
            { id: 124, img: "./images/1170.png", brand: "УАЗ", number: "1170", active: false },
            { id: 125, img: "./images/ВЕ7046ЕМ.png", brand: "Mitsubishi", number: "ВЕ 7046 ЕМ", active: false },
            { id: 126, img: "./images/BE7549EM.png", brand: "Mitsubishi Pajero", number: "BE 7549 EM", active: false },
            { id: 127, img: "./images/AA2300OE.png", brand: "Mercedes-Benz Matic", number: "AA 2300 OE", active: false },
            { id: 128, img: "./images/АА7785ВР.png", brand: "Volkswagen Touareg", number: "АА 7785 ВР", active: false },
            { id: 129, img: "./images/КА5257ВІ.png", brand: "Renault Trafic", number: "КА 5257 ВІ", active: false },
            { id: 130, img: "./images/КА0697СС.png", brand: "Skoda Octavia", number: "КА 0697 СС", active: false },
            { id: 131, img: "./images/AI4526IK.png", brand: "Dacia Sandero", number: "AI 4526 IK", active: false },
            { id: 132, img: "./images/АА4072ХВ.png", brand: "Ford Mondeo", number: "АА 4072 ХВ", active: false },
            { id: 133, img: "./images/АР6289АМ.jpg", brand: "Karsan J9", number: "АР 6289 АМ", active: false }, 
            { id: 134, img: "./images/АР4987СР.jpg", brand: "Mitsubishi Pajero", number: "АР 4987 СР", active: false },
            { id: 135, img: "./images/АР9038АВ.png", brand: "Fiat", number: "АР 9038 АВ", active: false },
            { id: 136, img: "./images/no-image.png", brand: "Chevrolet Cruze", number: "АР 2034 ЕР", active: false },
            { id: 137, img: "./images/AA4007ХВ.jpg", brand: "Mercedes-Benz Sprinter", number: "АА 4007 ХВ", active: false },
            //{ img: "./images/no-image.png", brand: " ", number: " " }, 
            //{ img: "./images/no-image.png", brand: " ", number: " " }, 
            //{ img: "./images/no-image.png", brand: " ", number: " " }, 
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " }, 
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " }, 
            //{ img: "./images/no-image.png", brand: " ", number: " " }, 
            //{ img: "./images/no-image.png", brand: " ", number: " " }, 
            //{ img: "./images/no-image.png", brand: " ", number: " " }, 
            //{ img: "./images/no-image.png", brand: " ", number: " " }, 
            //{ img: "./images/no-image.png", brand: " ", number: " " }, 
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " }, 
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " },
            //{ img: "./images/no-image.png", brand: " ", number: " " }, 
            //{ img: "./images/no-image.png", brand: " ", number: " " }, 
            //{ img: "./images/no-image.png", brand: " ", number: " " }, 
        ];
